Fix/ole emf header alternative
EPPlusSoftware/EPPlus pull request #1622
Opened 2024-10-10 14:02 UTC by OssianEPPlus

Before submitting this pull request I have...
- [X] read EPPlus Softwares [Contribution Guidlines](CONTRIBUTING.md)
- [X] ensured that the functionality I have added/changed is covered by new unit tests.
- [X] merged the target branch into the PR branch and resolved any merge conflicts
- [X] Run all the unit tests and ensured that they all are green (unless the purpose of the PR is to provide us with failing unit tests).

Added alternate headers and font handling.
Also added correct character spacing for emf files based on fonts

2024-10-11 07:22 UTC, swmal requested changes
Looks very good. I have added comments in this review where code has been disabled with comments.

2024-10-11 07:22 UTC, swmal commented on src/EPPlusTest/EmfTest.cs
Commented code on line 64

2024-10-11 07:22 UTC, swmal commented on src/EPPlus/Drawing/EMF/Records/EMR_EXTCREATEFONTINDIRECTW.cs
Commented code on line 46-51

2024-10-11 07:22 UTC, swmal commented on src/EPPlus/Drawing/EMF/Records/EMR_EXTTEXTOUTW.cs
Commented code on line 68 and 69

2024-10-11 07:22 UTC, swmal commented on src/EPPlus/Drawing/EMF/Records/EMR_HEADER.cs
Commented code on line 142-143

2024-10-11 07:22 UTC, swmal commented on src/EPPlus/Drawing/EMF/Enums/MapModeEnum.cs
Commented code on lines 50-57

2024-10-22 14:38 UTC, JanKallman commented on src/EPPlus/Core/Worksheet/Fonts/GenericFontMetrics/GenericFontMetricsTextMeasurer.cs
> +using System.Drawing;
Should be removed?

2024-10-23 07:42 UTC, OssianEPPlus commented on src/EPPlus/Core/Worksheet/Fonts/GenericFontMetrics/GenericFontMetricsTextMeasurer.cs
> +using System.Drawing;
yep

2024-10-23 07:43 UTC, OssianEPPlus commented on src/EPPlus/Drawing/EMF/Enums/MapModeEnum.cs
Fixed

2024-10-23 07:44 UTC, OssianEPPlus commented on src/EPPlus/Drawing/EMF/Records/EMR_EXTCREATEFONTINDIRECTW.cs
fixed

2024-10-23 07:44 UTC, OssianEPPlus commented on src/EPPlus/Drawing/EMF/Records/EMR_EXTTEXTOUTW.cs
fixed

2024-10-23 07:59 UTC, OssianEPPlus commented on src/EPPlus/Drawing/EMF/Records/EMR_HEADER.cs
Fixed. Do note that we Might need the values again some day. If so, refer to this github comment to find them.

```
//Bounds = new byte[16] { 0x13, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x4b, 0x00, 0x00, 0x00, 0x30, 0x00, 0x00, 0x00 };
//Frame = new byte[16] { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xBD, 0x08, 0x00, 0x00, 0x90, 0x06, 0x00, 0x00 };
```

2024-10-23 07:59 UTC, OssianEPPlus commented on src/EPPlusTest/EmfTest.cs
fixed

2024-10-24 06:42 UTC, merged